# Generated by Django 3.1 on 2021-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210223_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adds_classic',
        ),
        migrations.AddField(
            model_name='profile',
            name='genres',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
