# Generated by Django 3.1.7 on 2021-07-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_book_bookcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='category_rank',
            field=models.IntegerField(unique=True),
        ),
    ]
