# Generated by Django 3.1.7 on 2021-07-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210726_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='genres',
        ),
        migrations.AddField(
            model_name='profile',
            name='genre_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre_4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre_5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
