# Generated by Django 3.1 on 2021-03-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210305_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.AddField(
            model_name='genre',
            name='has_autobiography',
            field=models.BooleanField(default=False, verbose_name='Autobiography'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_biography',
            field=models.BooleanField(default=False, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_drama',
            field=models.BooleanField(default=False, verbose_name='Drama'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_fairytale',
            field=models.BooleanField(default=False, verbose_name='Fairytale'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_fantasy',
            field=models.BooleanField(default=False, verbose_name='Fantasy'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_folktale',
            field=models.BooleanField(default=False, verbose_name='Folktale'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_historical_fiction',
            field=models.BooleanField(default=False, verbose_name='Historical Fiction'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_horror',
            field=models.BooleanField(default=False, verbose_name='Horror'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_informational',
            field=models.BooleanField(default=False, verbose_name='Informational'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_mystery',
            field=models.BooleanField(default=False, verbose_name='Mystery'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_myth',
            field=models.BooleanField(default=False, verbose_name='Myth'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_poetry',
            field=models.BooleanField(default=False, verbose_name='Poetry'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_realistic_fiction',
            field=models.BooleanField(default=False, verbose_name='Realistic Fiction'),
        ),
        migrations.AddField(
            model_name='genre',
            name='has_science_fiction',
            field=models.BooleanField(default=False, verbose_name='Science Fiction'),
        ),
    ]
