# Generated by Django 3.1.7 on 2021-07-27 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20210727_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_all_user_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
