# Generated by Django 3.1.7 on 2021-07-27 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_userreadlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='genre_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genre_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genre_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genre_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genre_5',
        ),
        migrations.CreateModel(
            name='UserGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bookcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_all_user_genres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
