# Generated by Django 3.1.7 on 2021-07-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210727_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
