# Generated by Django 3.1 on 2021-03-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
