# Generated by Django 3.1 on 2021-03-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.CharField(max_length=500),
        ),
    ]
