# Generated by Django 3.1 on 2021-03-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210309_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_post',
            new_name='post_image',
        ),
    ]
